//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookyourdoctor
{
    using System;
    using System.Collections.Generic;
    
    public partial class appointment
    {
        public string appointment_id { get; set; }
        public string patient_id { get; set; }
        public string office_id { get; set; }
        public System.DateTime appointment_datetime { get; set; }
    
        public virtual office office { get; set; }
        public virtual patient patient { get; set; }
    }
}
