//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookyourdoctor
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctor_specialization
    {
        public string id { get; set; }
        public string doctor_id { get; set; }
        public string specialization_id { get; set; }
    
        public virtual doctor doctor { get; set; }
        public virtual specialization specialization { get; set; }
    }
}
